"""Create and populate the SpecMatch database in Supabase PostgreSQL.

Run from backend/ after setting DATABASE_URL in backend/.env:
    python scripts/migrate_supabase.py

The script is repeatable: tables are created if absent and CSV rows use
ON CONFLICT DO NOTHING. Use --reset only when the Supabase project is empty
or you intentionally want to replace its data.
"""

import argparse
import csv
import re
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.config import DATA_DIR, DATABASE_URL, IS_POSTGRES
from scripts.import_dataset import CSV_IMPORT_MAP


BASE_DIR = Path(__file__).resolve().parent
SCHEMA_PATH = BASE_DIR / "schema.sql"


def postgres_schema() -> list[str]:
    """Convert the shared SQLite DDL into PostgreSQL-compatible statements."""
    source = SCHEMA_PATH.read_text(encoding="utf-8")
    source = re.sub(
        r"INTEGER\s+PRIMARY KEY\s+AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        source,
        flags=re.IGNORECASE,
    )
    source = re.sub(r"\bREAL\b", "DOUBLE PRECISION", source, flags=re.IGNORECASE)
    source = re.sub(r"\bBLOB\b", "BYTEA", source, flags=re.IGNORECASE)
    return [statement.strip() for statement in source.split(";") if statement.strip()]


def ensure_schema(conn) -> None:
    with conn.cursor() as cur:
        cur.execute("CREATE EXTENSION IF NOT EXISTS vector")
        for statement in postgres_schema():
            cur.execute(statement)
        cur.execute("ALTER TABLE standards ADD COLUMN IF NOT EXISTS embedding vector(384)")
        cur.execute("ALTER TABLE standards ADD COLUMN IF NOT EXISTS search_vector tsvector")
        cur.execute("""
            UPDATE standards
            SET search_vector = to_tsvector(
                'simple', concat_ws(' ', standard_number, title, title_normalized,
                                    derived_keywords, standard_family_key, department,
                                    committee, sector, product_category, scope)
            )
            WHERE search_vector IS NULL
        """)
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_standards_search_vector
            ON standards USING gin(search_vector)
        """)
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_standards_embedding_hnsw
            ON standards USING hnsw (embedding vector_cosine_ops)
        """)
        cur.execute("""
            CREATE OR REPLACE FUNCTION standards_search_vector_update() RETURNS trigger
            LANGUAGE plpgsql AS $$
            BEGIN
                NEW.search_vector := to_tsvector(
                    'simple', concat_ws(' ', NEW.standard_number, NEW.title,
                    NEW.title_normalized, NEW.derived_keywords,
                    NEW.standard_family_key, NEW.department, NEW.committee,
                    NEW.sector, NEW.product_category, NEW.scope));
                RETURN NEW;
            END $$
        """)
        cur.execute("DROP TRIGGER IF EXISTS trg_standards_search_vector ON standards")
        cur.execute("""
            CREATE TRIGGER trg_standards_search_vector
            BEFORE INSERT OR UPDATE ON standards
            FOR EACH ROW EXECUTE FUNCTION standards_search_vector_update()
        """)


def reset_tables(conn) -> None:
    tables = [table for _, table, _ in CSV_IMPORT_MAP]
    with conn.cursor() as cur:
        cur.execute("TRUNCATE TABLE " + ", ".join(f'"{table}"' for table in tables) + " RESTART IDENTITY CASCADE")


def table_columns(conn, table_name: str) -> set[str]:
    with conn.cursor() as cur:
        cur.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema = 'public' AND table_name = %s",
            (table_name,),
        )
        return {row[0] for row in cur.fetchall()}


def import_csv(conn, csv_rel_path: str, table_name: str) -> int:
    csv_path = DATA_DIR / csv_rel_path
    if not csv_path.exists():
        print(f"SKIP {csv_rel_path}")
        return 0

    columns = table_columns(conn, table_name)
    with csv_path.open("r", encoding="utf-8", newline="") as file:
        reader = csv.DictReader(file)
        csv_columns = [column for column in (reader.fieldnames or []) if column in columns]
        if not csv_columns:
            print(f"SKIP {csv_rel_path}: no matching columns")
            return 0
        quoted_table = f'"{table_name}"'
        quoted_columns = ", ".join(f'"{column}"' for column in csv_columns)
        placeholders = ", ".join(["%s"] * len(csv_columns))
        sql = f"INSERT INTO {quoted_table} ({quoted_columns}) VALUES ({placeholders}) ON CONFLICT DO NOTHING"
        rows = []
        count = 0
        with conn.cursor() as cur:
            for row in reader:
                rows.append(tuple(None if row.get(column, "") in ("", "NOT_AVAILABLE") else row.get(column) for column in csv_columns))
                if len(rows) >= 1000:
                    cur.executemany(sql, rows)
                    count += len(rows)
                    rows = []
            if rows:
                cur.executemany(sql, rows)
                count += len(rows)
    print(f"OK {csv_rel_path} -> {table_name}: {count} rows")
    return count


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reset", action="store_true", help="truncate imported tables before loading CSVs")
    args = parser.parse_args()
    if not IS_POSTGRES:
        print("DATABASE_URL must be a postgresql:// or postgres:// URL")
        return 2

    import psycopg

    started = time.time()
    print("Connecting to Supabase PostgreSQL...")
    with psycopg.connect(DATABASE_URL) as conn:
        ensure_schema(conn)
        if args.reset:
            reset_tables(conn)
        total = sum(import_csv(conn, path, table) for path, table, _ in CSV_IMPORT_MAP)
        conn.commit()
        with conn.cursor() as cur:
            cur.execute("SELECT COUNT(*) FROM standards")
            standards_count = cur.fetchone()[0]
    print(f"Imported {total} CSV rows; standards={standards_count}; elapsed={time.time() - started:.1f}s")
    if standards_count < 24000:
        print("WARNING: expected approximately 24,132 standards")
        return 1
    print("Supabase migration complete.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
